steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'me-central1-docker.pkg.dev/applab-poc-project-02/poc-application/frontend:$SHORT_SHA'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'me-central1-docker.pkg.dev/applab-poc-project-02/poc-application/frontend:$SHORT_SHA'
images:
  - 'me-central1-docker.pkg.dev/applab-poc-project-02/poc-application/frontend:$SHORT_SHA'
